version: '3.8'
services:
  portainer:
    build: ./portainer
    container_name: irumesh-portainerc
    image: irumesh-portaineri
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command:
   #   - '-H unix:///var/run/docker.sock'
      - '--admin-password-file=/run/secrets/portainer_admin_password'
      - '--no-analytics'
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    networks:
      - iot-network
    ports:
      - "9000:9000"
    secrets:
      - portainer_admin_password


networks:
  iot-network:
    driver: bridge

volumes:
  portainer_data:

secrets:
  portainer_admin_password:
    file: ./portainer/portainer_admin_password


 