version: "3.8"
#https://docs.portainer.io/advanced/cli
services:
  portainer:
    build:
      context: portainer/
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    environment:
      - VIRTUAL_PORT=9000
    networks:
      - iot-network
    ports:
      - 9000:9000
    

volumes:
  portainer_data:


networks:
  iot-network: 
    driver: bridge
