version: '3.8'

services:

  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: irumesh-mosquittoi
    container_name: irumesh-mosquittoc
    restart: always
    ports:
      - 1883:1883
    volumes:
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
    networks:
      - iot-network


volumes:
  data:
  log:

networks:
  iot-network: 
    driver: bridge