version: '3.8'

services:
# ==============================================================================
  # nodered
  nodered:
    build: ./node-red
    image: irumesh-node-redi
    container_name: irumesh-node-redc
    environment:
      - TZ=Asia/Colombo
      - NODE_RED_USERNAME=${NODERED_USERNAME}
      - NODE_RED_PASSWORD=${NODERED_PASSWORD}
    restart: always
    ports:
      - "1880:1880" #Host:container
    volumes:
      - node-red-data:/data
    networks:
      - iot-network
# ==============================================================================
  # Eclipse Mosquitto MQTT Broker
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: irumesh-mosquittoi
    container_name: irumesh-mosquittoc
    restart: always
    ports:
      - 1883:1883
    volumes:
      - /mosquitto/data:/mosquitto/data
      - /mosquitto/log:/mosquitto/log
    networks:
      - iot-network
# ==============================================================================
  portainer:
    build:
      context: ./portainer
    command: -H unix:///var/run/docker.sock
    image: irumesh-portaineri
    container_name: irumesh-portainerc
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"
    environment:
      - VIRTUAL_PORT=9000
    networks:
        - iot-network
    ports:
      - 9000:9000

# ============================================================================== 
volumes:
  node-red-data:
  data:
  log:
  portainer_data:


networks:
  iot-network: 
    driver: bridge
