services:
  grafana:
    image: irumesh-grafanai
    build:
      context: ./grafana
    container_name: irumesh-grafana
    restart: unless-stopped
    env_file:
      - './grafana/.env'
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    # user: "472"
    ports:
      - 3000:3000/tcp
    # adding the mount volume point which we create earlier
    volumes:
    #   # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/grafana_data/plugins:/var/lib/grafana/plugins

    networks:
      - internal


volumes:
  grafana_data:
    external: true

networks:
  internal:
    driver: bridge