services:
  influxdb:
    image: influxdb:3.3.0-core
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-config:/etc/influxdb
      # modify after creating
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123
      - INFLUXDB3_NODE_IDENTIFIER_PREFIX=my-node
      - INFLUXDB3_OBJECT_STORE=file
      - INFLUXDB3_DB_DIR=/var/lib/influxdb3
      - LOG_FILTER=info
    networks:
      - iot-network

volumes:
  influxdb-data:
  influxdb-config:

networks:
  iot-network:
    driver: bridge
