FROM grafana/grafana-oss:12.1.0

# Label the image for better tracking and metadata
LABEL maintainer="Rumesh>" \
      description="Grafana for IoT" \
      version="12.2.0"


# Healthcheck to ensure Grafana is running
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3000/api/health || exit 1

# Expose Grafana default port
EXPOSE 3000


